<?php

use App\Backup\BackupException;
use App\Backup\BackupService;
use App\Backup\RestoreService;
use App\Models\Backup;
use App\Models\Consignment;
use App\Models\ConsignmentAdjustment;
use App\Models\ConsignmentItem;
use App\Models\ConsignmentPartner;
use App\Models\ConsignmentSale;
use App\Models\ConsignmentSettlement;
use App\Models\Customer;
use App\Models\Product;
use App\Models\PurchaseOrder;
use App\Models\PurchaseOrderItem;
use App\Models\Refund;
use App\Models\Sale;
use App\Models\SaleItem;
use App\Models\StockMovement;
use App\Models\Supplier;
use App\Models\User;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;

/**
 * Every table that carries POS, inventory, procurement or consignment state.
 *
 * A backup that silently loses any of these is not a usable backup, so each one
 * is checked for both presence and exact contents.
 *
 * @var array<int, string>
 */
const BUSINESS_TABLES = [
    'users',
    'customers',
    'products',
    'sales',
    'sale_items',
    'refunds',
    'suppliers',
    'stock_movements',
    'purchase_orders',
    'purchase_order_items',
    'consignment_partners',
    'consignments',
    'consignment_items',
    'consignment_sales',
    'consignment_adjustments',
    'consignment_settlements',
    'backups',
    'activity_logs',
];

/**
 * Tables that must never end up in a backup: they are runtime state, they are
 * regenerated by the application, and restoring stale queue or session rows can
 * resurrect work that was already done.
 *
 * @var array<int, string>
 */
const TRANSIENT_TABLES = [
    'jobs',
    'job_batches',
    'failed_jobs',
    'sessions',
    'cache',
    'cache_locks',
];

/**
 * Build a representative business day across every part of the POS.
 *
 * @return array<string, int>
 */
function seedBusinessData(): array
{
    $cashier = User::factory()->inventoryStaff()->create();
    $manager = User::factory()->manager()->create();

    $customer = Customer::factory()->create(['name' => 'Akoto Farms Ltd']);
    $supplier = Supplier::factory()->create(['name' => 'Asante Agro Supplies']);

    $product = Product::factory()->create([
        'name' => 'Apex 25EC',
        'batch_number' => 'BATCH-2026-A',
        'price' => 145.50,
        'stock' => 320.00,
    ]);

    $sale = Sale::factory()->create([
        'customer_id' => $customer->id,
        'subtotal' => 291.00,
        'total' => 291.00,
        'payment_method' => 'cash',
    ]);

    SaleItem::factory()->create([
        'sale_id' => $sale->id,
        'product_id' => $product->id,
        'quantity' => 2,
        'unit_price' => 145.50,
        'line_total' => 291.00,
    ]);

    Refund::factory()->create(['sale_id' => $sale->id]);

    StockMovement::factory()->outgoing()->create([
        'product_id' => $product->id,
        'quantity' => -2,
        'user_id' => $cashier->id,
    ]);

    $purchaseOrder = PurchaseOrder::factory()->received()->create([
        'supplier_id' => $supplier->id,
        'created_by' => $manager->id,
        'total' => 1200.00,
    ]);

    PurchaseOrderItem::factory()->create([
        'purchase_order_id' => $purchaseOrder->id,
        'product_id' => $product->id,
        'quantity' => 24,
        'unit_cost' => 50.00,
        'line_total' => 1200.00,
    ]);

    $partner = ConsignmentPartner::factory()->create(['name' => 'Mensah Cooperative']);

    $consignment = Consignment::factory()->create([
        'partner_id' => $partner->id,
        'received_at' => now()->toDateString(),
    ]);

    $consignmentItem = ConsignmentItem::factory()->create([
        'consignment_id' => $consignment->id,
        'product_id' => $product->id,
        'quantity' => 40,
        'unit_cost' => 30.00,
        'line_total' => 1200.00,
    ]);

    ConsignmentSale::factory()->create([
        'partner_id' => $partner->id,
        'sale_id' => $sale->id,
        'customer_id' => $customer->id,
        'product_id' => $product->id,
        'quantity' => 5,
        'unit_price' => 100.00,
        'line_total' => 500.00,
        'payable_amount' => 500.00,
        'sold_at' => now(),
    ]);

    ConsignmentAdjustment::factory()->create([
        'partner_id' => $partner->id,
        'product_id' => $product->id,
        'quantity' => -2,
        'reason' => 'damaged',
        'value' => 60.00,
        'adjusted_at' => now()->toDateString(),
    ]);

    ConsignmentSettlement::factory()->create([
        'partner_id' => $partner->id,
        'amount' => 250.00,
        'settled_at' => now()->toDateString(),
    ]);

    return [
        'users' => User::count(),
        'customers' => Customer::count(),
        'products' => Product::count(),
        'sales' => Sale::count(),
        'sale_items' => SaleItem::count(),
        'refunds' => Refund::count(),
        'suppliers' => Supplier::count(),
        'stock_movements' => StockMovement::count(),
        'purchase_orders' => PurchaseOrder::count(),
        'purchase_order_items' => PurchaseOrderItem::count(),
        'consignment_partners' => ConsignmentPartner::count(),
        'consignments' => Consignment::count(),
        'consignment_items' => ConsignmentItem::count(),
        'consignment_sales' => ConsignmentSale::count(),
        'consignment_adjustments' => ConsignmentAdjustment::count(),
        'consignment_settlements' => ConsignmentSettlement::count(),
    ];
}

/**
 * Replay a gzipped dump into a brand new SQLite database and return the handle.
 *
 * This is the closest a test can get to a real restore: an empty database is
 * rebuilt purely from the backup artifact.
 *
 * @return array{0: PDO, 1: string}
 */
function replayDumpIntoFreshDatabase(Backup $backup): array
{
    $sql = (string) gzdecode((string) Storage::disk($backup->disk)->get($backup->path));
    $path = tempnam(sys_get_temp_dir(), 'vfprestore-').'.sqlite';

    $pdo = new PDO('sqlite:'.$path);
    $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
    $pdo->exec($sql);

    return [$pdo, $path];
}

/**
 * Read a whole table out of the replayed database.
 *
 * @return array<int, array<string, mixed>>
 */
function rowsFrom(PDO $pdo, string $table): array
{
    return $pdo->query('SELECT * FROM "'.$table.'" ORDER BY id')->fetchAll(PDO::FETCH_ASSOC);
}

beforeEach(function () {
    useBackupTestingDisk();
});

test('a database backup contains every business table and no runtime state', function () {
    seedBusinessData();

    $service = app(BackupService::class);
    $backup = $service->run($service->request(Backup::TYPE_DATABASE));

    expect($backup->isCompleted())->toBeTrue();

    $sql = (string) gzdecode((string) Storage::disk($backup->disk)->get($backup->path));

    foreach (BUSINESS_TABLES as $table) {
        expect($sql)->toContain('Table structure for '.$table);
    }

    foreach (TRANSIENT_TABLES as $table) {
        expect($sql)->not->toContain('Table structure for '.$table);
    }
});

test('a backup can rebuild an empty database with the exact same business rows', function () {
    $expected = seedBusinessData();

    $service = app(BackupService::class);
    $backup = $service->run($service->request(Backup::TYPE_DATABASE));

    [$pdo, $path] = replayDumpIntoFreshDatabase($backup);

    try {
        // The rebuilt database starts from nothing, so everything in it came
        // from the artifact alone.
        foreach (BUSINESS_TABLES as $table) {
            expect($pdo->query("SELECT COUNT(*) FROM sqlite_master WHERE type = 'table' AND name = '{$table}'")->fetchColumn())
                ->toBe(1, "Table [{$table}] is missing from the dump.");
        }

        expect(rowsFrom($pdo, 'customers')[0]['name'])->toBe('Akoto Farms Ltd')
            ->and(rowsFrom($pdo, 'suppliers')[0]['name'])->toBe('Asante Agro Supplies')
            ->and(rowsFrom($pdo, 'products')[0]['batch_number'])->toBe('BATCH-2026-A')
            ->and((float) rowsFrom($pdo, 'products')[0]['stock'])->toBe(320.0)
            ->and((float) rowsFrom($pdo, 'sale_items')[0]['unit_price'])->toBe(145.5)
            ->and((float) rowsFrom($pdo, 'stock_movements')[0]['quantity'])->toBe(-2.0)
            ->and(rowsFrom($pdo, 'stock_movements')[0]['type'])->toBe('out')
            ->and(rowsFrom($pdo, 'purchase_orders')[0]['status'])->toBe('received')
            ->and((float) rowsFrom($pdo, 'purchase_order_items')[0]['unit_cost'])->toBe(50.0)
            ->and((float) rowsFrom($pdo, 'consignment_items')[0]['quantity'])->toBe(40.0)
            ->and((float) rowsFrom($pdo, 'consignment_sales')[0]['payable_amount'])->toBe(500.0)
            ->and(rowsFrom($pdo, 'consignment_partners')[0]['name'])->toBe('Mensah Cooperative')
            ->and(rowsFrom($pdo, 'consignment_adjustments')[0]['reason'])->toBe('damaged')
            ->and((float) rowsFrom($pdo, 'consignment_settlements')[0]['amount'])->toBe(250.0);

        // Row counts match the live database table for table.
        foreach ($expected as $table => $count) {
            expect(rowsFrom($pdo, $table))->toHaveCount($count, "Row count for [{$table}] does not match the live database.");
        }

        // The backup's own row is inside its artifact. It was written while the
        // dump was still being produced, so it is reconciled after the import
        // rather than left looking like work that is still in progress.
        expect(rowsFrom($pdo, 'backups')[0]['filename'])->toBe($backup->filename)
            ->and(rowsFrom($pdo, 'backups')[0]['status'])->toBe(Backup::STATUS_RUNNING)
            ->and(rowsFrom($pdo, 'activity_logs'))->not->toBeEmpty();

        // Nullable foreign keys and timestamps survived rather than being
        // flattened to empty strings.
        $sale = rowsFrom($pdo, 'sales')[0];

        expect(array_key_exists('customer_id', $sale))->toBeTrue()
            ->and($sale['payment_method'])->toBe('cash')
            ->and($sale['created_at'])->not->toBeEmpty()
            ->and($sale['updated_at'])->not->toBeEmpty();
    } finally {
        unset($pdo);
        @unlink($path);
    }
});

test('a backup is a point in time snapshot, not a live view of the data', function () {
    $sale = Sale::factory()->create();
    $product = Product::factory()->create(['stock' => 500]);

    $service = app(BackupService::class);
    $backup = $service->run($service->request(Backup::TYPE_DATABASE));

    // Business activity continues after the dump was written.
    $sale->delete();
    $product->update(['stock' => 0]);
    Sale::factory()->count(5)->create();
    Product::factory()->create(['name' => 'Post-backup arrival']);

    [$pdo, $path] = replayDumpIntoFreshDatabase($backup);

    try {
        expect(rowsFrom($pdo, 'sales'))->toHaveCount(1)
            ->and(rowsFrom($pdo, 'sales')[0]['id'])->toBe($sale->id)
            ->and((float) rowsFrom($pdo, 'products')[0]['stock'])->toBe(500.0)
            ->and(collect(rowsFrom($pdo, 'products'))->pluck('name')->all())->not->toContain('Post-backup arrival');
    } finally {
        unset($pdo);
        @unlink($path);
    }
});

test('a full backup carries both the database and the archived business files', function () {
    seedBusinessData();

    writeBackupFixture('dbjsons/settings.json', '{"currency":"GHS","shop":"Kumasi"}');
    writeBackupFixture('public/uploads/logo.png', 'fake-png-bytes');
    writeBackupFixture('skip/secret.txt', 'must not be archived');
    writeBackupFixture('debug.log', 'must not be archived');

    $service = app(BackupService::class);
    $backup = $service->run($service->request(Backup::TYPE_FULL));

    $entries = zipEntriesOf($backup);
    $root = 'files/storage/framework/testing/backup-fixtures/';

    expect($entries)->toContain('database.sql.gz')
        ->and($entries)->toContain($root.'dbjsons/settings.json')
        ->and($entries)->toContain($root.'public/uploads/logo.png')
        ->and(collect($entries)->filter(fn (string $entry) => str_contains($entry, 'secret.txt'))->all())->toBe([])
        ->and(collect($entries)->filter(fn (string $entry) => str_contains($entry, 'debug.log'))->all())->toBe([]);

    // The private backup directory and the staging work directory must never be
    // archived inside a backup, or a full backup would recurse into itself.
    expect(collect($entries)->filter(fn (string $entry) => str_contains($entry, 'backup-work'))->all())->toBe([])
        ->and(collect($entries)->filter(fn (string $entry) => str_contains($entry, 'backups/'))->all())->toBe([]);
});

test('a restore takes a safety backup of the data it is about to replace', function () {
    useRestorableBackups();
    seedBusinessData();

    $service = app(BackupService::class);
    $source = $service->run($service->request(Backup::TYPE_DATABASE));

    config([
        'backup.restore.safety_backup' => true,
        'backup.restore.maintenance_mode' => false,
    ]);

    try {
        app(RestoreService::class)->restore($source);
    } catch (Throwable) {
        // The import is expected to fail on SQLite; the safety backup is taken
        // before that point and must still exist.
    }

    $safety = Backup::where('type', Backup::TYPE_DATABASE)
        ->whereKeyNot($source->id)
        ->sole();

    expect($safety->status)->toBe(Backup::STATUS_COMPLETED)
        ->and($safety->size)->toBeGreaterThan(0)
        ->and(Storage::disk($safety->disk)->exists($safety->path))->toBeTrue()
        ->and($safety->checksum)->toBe(hash_file('sha256', Storage::disk($safety->disk)->path($safety->path)));

    // The safety backup is a usable, restorable artifact in its own right.
    [$pdo, $path] = replayDumpIntoFreshDatabase($safety);

    try {
        expect((float) rowsFrom($pdo, 'products')[0]['stock'])->toBe(320.0)
            ->and(rowsFrom($pdo, 'consignment_sales'))->toHaveCount(1);
    } finally {
        unset($pdo);
        @unlink($path);
    }

    // The live business data is untouched by a restore that never got as far
    // as importing.
    expect(DB::table('sales')->count())->toBeGreaterThan(0)
        ->and(DB::table('consignment_sales')->count())->toBeGreaterThan(0)
        ->and(DB::table('purchase_order_items')->count())->toBeGreaterThan(0);
});

test('a restore refuses to import over a non MySQL connection', function () {
    useRestorableBackups();

    $service = app(BackupService::class);
    $backup = $service->run($service->request(Backup::TYPE_DATABASE));

    config([
        'backup.restore.safety_backup' => false,
        'backup.restore.maintenance_mode' => false,
    ]);

    expect(fn () => app(RestoreService::class)->restore($backup))
        ->toThrow(BackupException::class, 'Only MySQL connections');
});
