<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Backup Disk
    |--------------------------------------------------------------------------
    |
    | The filesystem disk backups are written to. It must resolve to a private
    | location: backups contain every business record in the system and must
    | never be reachable through /public or /storage. The "local" disk is
    | rooted at storage/app/private.
    |
    */

    'disk' => env('BACKUP_DISK', 'local'),

    /*
    |--------------------------------------------------------------------------
    | Declared Private Disks
    |--------------------------------------------------------------------------
    |
    | The disks that are known to sit somewhere the web server cannot serve.
    | A disk must appear here *and* pass the structural check in
    | App\Backup\PrivateDisk before a backup may be written to it, so adding
    | the "public" disk has no effect. Add a remote disk here only after
    | confirming its bucket or container is not readable by anyone outside the
    | application; a public bucket would expose every record in the system.
    |
    */

    'private_disks' => array_filter(array_map(
        'trim',
        explode(',', (string) env('BACKUP_PRIVATE_DISKS', 'local'))
    )),

    /*
    |--------------------------------------------------------------------------
    | Backup Directory
    |--------------------------------------------------------------------------
    |
    | Directory inside the disk that holds every backup artifact. Backups are
    | never written outside of this directory.
    |
    */

    'directory' => env('BACKUP_DIRECTORY', 'backups'),

    /*
    |--------------------------------------------------------------------------
    | Filename Prefix
    |--------------------------------------------------------------------------
    |
    | Filenames are always generated by the application, never supplied by a
    | user. Format: {prefix}-{type}-{Y-m-d-His}.{extension}
    |
    */

    'filename_prefix' => env('BACKUP_FILENAME_PREFIX', 'villonfarm'),

    /*
    |--------------------------------------------------------------------------
    | Work Directory
    |--------------------------------------------------------------------------
    |
    | Local staging directory where a dump and an archive are assembled before
    | they are written to the backup disk. It sits on the private disk root so
    | it is never web reachable, and is always removed once the backup has
    | finished, successfully or not.
    |
    */

    'work_directory' => env('BACKUP_WORK_DIRECTORY'),

    /*
    |--------------------------------------------------------------------------
    | Included Paths
    |--------------------------------------------------------------------------
    |
    | Project-relative paths that are business critical and must be captured by
    | a "full" backup. Paths that do not exist are skipped silently so this
    | list can stay forward compatible. Never add vendor/, node_modules/,
    | .git/, storage/framework/, storage/logs/ or public/build/ here.
    |
    */

    'files' => [
        'storage/app/private',
        'public/uploads',
        'dbjsons',
    ],

    /*
    |--------------------------------------------------------------------------
    | Excluded Patterns
    |--------------------------------------------------------------------------
    |
    | Glob patterns, relative to each included path, that are never archived.
    | The backup directory is always excluded so a full backup can never recurse
    | into previous backups, and the staging work directory is always excluded
    | so a full backup can never archive the artifact it is still writing.
    |
    */

    'exclude' => [
        '**/.gitignore',
        '**/.DS_Store',
        '**/*.log',
        '**/backups/**',
        '**/backup-work/**',
    ],

    /*
    |--------------------------------------------------------------------------
    | Database Binaries
    |--------------------------------------------------------------------------
    |
    | Absolute paths to the MySQL client tools. Leave these null to let the
    | application discover them on PATH and in the usual install locations.
    | mysqldump is preferred for backups; when it is unavailable the
    | application falls back to a pure-PHP consistent snapshot. The mysql
    | client is only needed to restore, and the application refuses to restore
    | without it rather than attempting to parse SQL itself.
    |
    */

    'mysql' => [
        'dump_binary' => env('BACKUP_MYSQLDUMP_BINARY'),
        'client_binary' => env('BACKUP_MYSQL_BINARY'),
    ],

    /*
    |--------------------------------------------------------------------------
    | Excluded Tables
    |--------------------------------------------------------------------------
    |
    | Framework bookkeeping tables that carry no business value and would only
    | add noise or stale state to a restore. No business table may ever be
    | listed here: sales, sale items, payments, refunds, products, stock
    | movements, purchase orders, receiving, consignment, partners,
    | settlements, units, customers, suppliers, users and settings must all
    | be dumped so relationships stay intact.
    |
    */

    'exclude_tables' => [
        'sessions',
        'cache',
        'cache_locks',
        'jobs',
        'job_batches',
        'failed_jobs',
    ],

    /*
    |--------------------------------------------------------------------------
    | Queue
    |--------------------------------------------------------------------------
    |
    | Backups run on their own queue so a long dump never blocks a queue
    | worker that is also handling other application work. A database queue
    | connection is strongly recommended; with QUEUE_CONNECTION=sync the
    | browser request will block until the backup finishes.
    |
    | stalled_after_minutes is how long a queued backup may sit untouched
    | before the Backups screen warns that nothing is running the queue. A
    | host with no worker leaves jobs waiting forever with no error, so this
    | turns that silence into a visible instruction.
    |
    */

    'queue' => [
        'name' => env('BACKUP_QUEUE', 'backups'),
        'restore_name' => env('BACKUP_RESTORE_QUEUE', 'restores'),
        'connection' => env('BACKUP_QUEUE_CONNECTION'),
        'stalled_after_minutes' => (int) env('BACKUP_QUEUE_STALLED_MINUTES', 5),
    ],

    /*
    |--------------------------------------------------------------------------
    | Restore Safety
    |--------------------------------------------------------------------------
    |
    | Restoring replaces live POS, inventory and consignment data, so it is
    | switched off on a fresh install and an administrator turns it on from the
    | Backups screen. That switch is a row in the backup_settings table, not a
    | config value, so it never needs a terminal or a cleared config cache.
    |
    | Whenever a restore does run, the application still takes a safety backup
    | of the current database first, and puts the app into maintenance mode so
    | no sale, receipt or stock movement can be written while the database is
    | being replaced.
    |
    */

    'restore' => [
        'safety_backup' => true,
        'maintenance_mode' => env('BACKUP_RESTORE_MAINTENANCE_MODE', true),
    ],

    /*
    |--------------------------------------------------------------------------
    | Retention
    |--------------------------------------------------------------------------
    |
    | How many backups to keep per frequency. "keep" is a count of the most
    | recent completed backups in that group; older ones are removed by
    | backup:cleanup. Backups that are pending or running are never deleted.
    |
    */

    'retention' => [
        'daily' => (int) env('BACKUP_RETENTION_DAILY', 7),
        'weekly' => (int) env('BACKUP_RETENTION_WEEKLY', 4),
        'monthly' => (int) env('BACKUP_RETENTION_MONTHLY', 6),
    ],

    /*
    |--------------------------------------------------------------------------
    | Schedule
    |--------------------------------------------------------------------------
    |
    | Times used by the scheduled commands registered in routes/console.php.
    | Each is a 24 hour HH:MM value. Use BACKUP_SCHEDULE_* in .env to move
    | them without a code change.
    |
    */

    'schedule' => [
        'daily' => env('BACKUP_SCHEDULE_DAILY', '02:00'),
        'weekly' => env('BACKUP_SCHEDULE_WEEKLY', '03:00'),
        'monthly' => env('BACKUP_SCHEDULE_MONTHLY', '04:00'),
        'cleanup' => env('BACKUP_SCHEDULE_CLEANUP', '05:00'),
    ],

    /*
    |--------------------------------------------------------------------------
    | Timeout
    |--------------------------------------------------------------------------
    |
    | Maximum seconds a single backup job may run before it is killed.
    |
    */

    'timeout' => (int) env('BACKUP_TIMEOUT', 3600),

    /*
    |--------------------------------------------------------------------------
    | Statuses
    |--------------------------------------------------------------------------
    */

    'statuses' => [
        'pending',
        'running',
        'completed',
        'failed',
    ],

];
